export const OLD_LABOR_CASE_CONTRACT = Object.freeze({
  sourceName: "srcAccionesIncidentesLegal_OLD",
  omlKey: "u_V5MNUE0UKxJgerN6PZFQ",
  role: "Registered",
  controlKeys: Object.freeze([
    "bqGpnJaDR06ANLezxYhsfQ", "wa1a84qeOUCh3k_WXltBMQ",
    "GdB3Szoxo0qFh9wxkJfoKA", "S18GaCB4xkCx7ZXG75Rmdg",
    "ILANkptR2EKJjLTmWcbUWw", "Nd9CrZSTUUaddZYQRrUybw",
    "GhrqymMZJkicg4GQCOFlMw", "1Fr17VLSI0WGk7R6c3Il2Q",
    "RnX6hsfQyEO8HtZg15UFQw", "1Ox0j3b0DUCuyi5UT9Yc5A",
    "P1q+e_i810u_y04g1Cy1Qg", "kXHBf5s910eS_ZQlhPZx4g",
    "DjEGCRKrS0akfEHUl+FeMw", "sxqO9z88c0uElW11SVggrA",
    "w7Jhxn8Tikq8sUKWbnxtGA", "PG_BX2y0gEKC0CYJc5vtGA",
    "FH++C6PGV0aVBj9QDf0bnA", "skLVePnERkCPU+0YigcA7g",
    "qAe014vk50WHGEfiy1AKog", "SVtFK55X10iiylY7GEB3YQ",
    "3Fad1qsiyEGuEqaLave+bg", "sHxhB0a_+EKrNe9y67hFmg",
    "1ZKN8SkQB0K4v6cJRuY4rQ", "gn8xhr8lGku1rbZznqsSwg",
    "fLVLbrZmt0mMy+b2t9M2jw", "E+p9BQXmN0Gb_M_pjZSv5g",
  ]),
  clientActions: Object.freeze([
    "CerrarIncidenteOnClick", "Upload1OnChange", "EjecutarAccionOnClick",
    "DescargarEvidenciaOnClick", "DropdownNivelOnChanged", "CambioVariableClick",
    "EditarOnClick", "UploadNuevaOnChange",
    "GetTblAccionesIncidentesByCodigoIncidenteOnAfterFe",
    "DropReasignarResOnChanged", "DropdownPrioridadOnChanged",
    "GetIncidenteOnAfterFetch", "GuardarAccionOnClick", "CerrarOnClick",
    "CerrarPopOnClick", "PrioridadOnChanged", "OnParametersChanged",
    "LinkOnClick", "ResponsableSearchOnChanged", "ActualizarOnClick",
    "CerrarAccionPopClick", "OnSort", "ReasignarOnClick",
    "ActualizarDatosOnClick", "NuevaAccionOnClick", "AccionesSearchOnChanged",
    "PopCerrarIncidentesOnClick", "UploadincidenteOnChange",
  ]),
  dataSources: Object.freeze([
    "GetResponsables", "GetNivelPrioridad", "GetPrioridad", "GetCorreo",
    "GetPrimeraAccion", "GetNivelPermisos", "GetIncidenteSeleccionado",
    "GetIncidente", "GetTblIncidentesByCodigo", "GetPersonasReasignar",
    "GetAcciones", "GetTblAccionesIncidentesLegalsByCodigoIncidente",
  ]),
  unusedDataSources: Object.freeze(["GetPersonasReasignar"]),
  actionMenu: Object.freeze([
    { control: "IniciaAccion", key: "P1q+e_i810u_y04g1Cy1Qg", type: 1, operation: "start" },
    { control: "CerrarAccion", key: "kXHBf5s910eS_ZQlhPZx4g", type: 2, operation: "close" },
    { control: "AnularAccion", key: "DjEGCRKrS0akfEHUl+FeMw", type: 3, operation: "cancel" },
    { control: "ReasignarResponsable", key: "sxqO9z88c0uElW11SVggrA", type: 4, operation: "reassign" },
    { control: "ReasignarFecha", key: "w7Jhxn8Tikq8sUKWbnxtGA", type: 5, operation: "reschedule" },
  ]),
  table: Object.freeze({
    width: 1194.4,
    headerHeight: 48,
    headerBackground: "#222",
    headers: Object.freeze([
      "Nombre Acción", "Descripción", "Responsable", "Fecha Cierre",
      "Estado", "Evidencia", "Histórico", "",
    ]),
    columnWidths: Object.freeze([165.15, 144.075, 146.575, 143.8375, 168, 200, 145.15, 80.0125]),
  }),
  absentCurrentFeatures: Object.freeze([
    "GetChatByCaso", "GetPersonasAcciones", "GetPersonasLegal",
    "AceptarCambioEstadoOnClick", "GetPersonasAccionesOnAfterFetch",
    "CerrarPopupJustificacionOnClick", "CancelarCasoOnClick",
  ]),
});

